version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
    env_file:
      - .env    
  frontend:
    build:
      context: ./frontend
    command: yarn dev -- --host
    ports:
      - "5173:5173"
    working_dir: /app
    env_file:
      - .env   
    volumes:
      - ./frontend:/app
      - /app/node_modules 
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: